### ISSUE TITLE
Scope of project should be made clear

### ISSUE THREAD

**Issue by mnsc** [sebgrohn/tournie#1]
Hello my name is Mattias and I run a popular hockey tournament at Trimma AB. I'm coding stuff against the Challonge API and am interested in the scope and ambitions of this project!??!

;)

**Comment by sebgrohn** [comment]
Thanks for showing interest in this. :) Now, you forced me to structure the work on this a bit more, a good thing!

I have now moved the project goals, "release plan", etc. that we had in a separate document to the wiki, so that is is more clear what we are aiming for.
