### ISSUE TITLE
Unnecessary call to fetchMembers

### ISSUE THREAD

**Issue by CurriedFloat** [sebgrohn/tournie#27]
https://github.com/sebgrohn/tournie/blob/08c85f148fc1cb0e71ab1e368c766c1e14cea139/src/handlers.js#L90

https://github.com/sebgrohn/tournie/blob/08c85f148fc1cb0e71ab1e368c766c1e14cea139/src/handlers.js#L97

Move above IF-statement and remove one

**Comment by sebgrohn** [comment]
Yes, you're right! I did think about it when I wrote that code, but left it like that because the calls where closer to where they were used. (Only one will be called.) But I think you convinced me to dedupe them. :)

**Comment by CurriedFloat** [comment]
Yeah, and if the two case were broken out into functions, you would want to inject the member list. 
Something like:
`const member = await challongeService.fetchMembers();
 return challongeUsername ? case1(userRepo, members) : case2(members);`

**Comment by CurriedFloat** [comment]
Or maybe then you would inject the service instead, not sure I convinced myself there...
