### ISSUE TITLE
Use R.evolve instead

### ISSUE THREAD

**Issue by CurriedFloat** [sebgrohn/tournie#32]
https://github.com/sebgrohn/tournie/blob/264e99ab96a2eaac84fad0d01189caaf71318c13/src/challonge.service.js#L33

https://ramdajs.com/docs/#evolve

**Comment by sebgrohn** [comment]
Is `evolve` smart enough to return the original object if all transformation functions would return their original values?

**Comment by CurriedFloat** [comment]
> Is `evolve` smart enough to return the original object if all transformation functions would return their original values?

My guess is no. https://github.com/ramda/ramda/blob/v0.26.1/source/evolve.js

**Comment by sebgrohn** [comment]
I think I am convinced. :) Should be done as part of #30.
