### ISSUE TITLE
Use R.chain instead

### ISSUE THREAD

**Issue by CurriedFloat** [sebgrohn/tournie#36]
https://github.com/sebgrohn/tournie/blob/ee142c87fb4735c46bc73efb7bf56254fc981699/src/challonge.service.js#L73

https://github.com/sebgrohn/tournie/blob/ee142c87fb4735c46bc73efb7bf56254fc981699/src/challonge.service.js#L79

https://github.com/sebgrohn/tournie/blob/ee142c87fb4735c46bc73efb7bf56254fc981699/src/handlers.js#L122

`map |> unnest`  is flatMap right?
https://ramdajs.com/docs/#chain

**Comment by sebgrohn** [comment]
Yes, you're right,  map |> unnest is `flatMap` / `chain`. Good catch!
